// Basic Class declaration, note absence of destructor
// a destructor will be automatically generated by the compiler

class cylinder
{
	protected:
		float radius;
		float height;
	public:
		float GetVolume();
		float GetSurface();
	
		cylinder (float, float);
};
